In [1]:
import numpy as np

mat1 = np.empty((3,3))
mat2 = np.empty((3,3))
print("Enter the matrix elements : ")
for i in range(0,3):
    for j in range(0,3):
        mat1[i][j] = int(input(f"Enter elements {i},{j} of matrix 1 : "))
        mat2[i][j] = int(input(f"Enter elements {i},{j} of matrix 2 : "))
print("matrix 1 \n",mat1)
print("matrix 2 \n",mat2)


Enter the matrix elements : 
matrix 1 
 [[1. 3. 5.]
 [7. 9. 2.]
 [4. 6. 8.]]
matrix 2 
 [[2. 4. 6.]
 [8. 1. 3.]
 [5. 7. 9.]]


In [2]:
print("Direct multiplication")
print(mat1*mat2)
print("Matrrix multiplcation")
print(np.dot(mat1,mat2))

Direct multiplication
[[ 2. 12. 30.]
 [56.  9.  6.]
 [20. 42. 72.]]
Matrrix multiplcation
[[ 51.  42.  60.]
 [ 96.  51.  87.]
 [ 96.  78. 114.]]


In [3]:
print("Matrix 1 transpose")
print(np.transpose(mat1))
print("Matrix 2 transpose")
print(np.transpose(mat2))

Matrix 1 transpose
[[1. 7. 4.]
 [3. 9. 6.]
 [5. 2. 8.]]
Matrix 2 transpose
[[2. 8. 5.]
 [4. 1. 7.]
 [6. 3. 9.]]


In [4]:
print("Matrix 1 trace")
print(np.trace(mat1))
print("Matrix 2 trace")
print(np.trace(mat2))

Matrix 1 trace
18.0
Matrix 2 trace
12.0


In [5]:
print("Rank of matrix 1")
print(np.linalg.matrix_rank(mat1))
print("Rank of matrix 2")
print(np.linalg.matrix_rank(mat2))

Rank of matrix 1
3
Rank of matrix 2
3


In [6]:
print("Determinant of matrix 1\n")
print(np.linalg.det(mat1))
print("\nDeterminant of matrix 2\n")
print(np.linalg.det(mat2))

Determinant of matrix 1

-54.00000000000001

Determinant of matrix 2

53.99999999999996


In [7]:
print("Inverse of matrix 1\n")
print(np.linalg.inv(mat1))
print("\nInverse of matrix 2\n")
print(np.linalg.inv(mat2))

Inverse of matrix 1

[[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]

Inverse of matrix 2

[[-0.22222222  0.11111111  0.11111111]
 [-1.05555556 -0.22222222  0.77777778]
 [ 0.94444444  0.11111111 -0.55555556]]


In [8]:
print("Eigen values of matrix 1\n")
print(np.linalg.eigvals(mat1))
print("\nEigen vectors of matrix 1\n")
print(np.linalg.eig(mat1)[1])
print("\nEigen values of matrix 2\n")
print(np.linalg.eigvals(mat2))
print("\nEigen vectors of matrix 2\n")
print(np.linalg.eig(mat2)[1])

Eigen values of matrix 1

[15.4422907  -0.98661655  3.54432584]

Eigen vectors of matrix 1

[[ 0.36886455  0.81664483  0.37173179]
 [ 0.61669356 -0.57673733 -0.7003462 ]
 [ 0.69543367  0.02157037  0.60936908]]

Eigen values of matrix 2

[15.66678757+0.j         -1.83339378+0.29231685j -1.83339378-0.29231685j]

Eigen vectors of matrix 2

[[ 0.46476339+0.j          0.11633808-0.04397186j  0.11633808+0.04397186j]
 [ 0.4136381 +0.j         -0.85691385+0.j         -0.85691385-0.j        ]
 [ 0.78287835+0.j          0.49908991+0.03376151j  0.49908991-0.03376151j]]
