In [1]:
#1 Convert Farenheit to Celsius
import numpy as np
fr=np.array([32,11,77,100])
# fr = int(input("Enter a number in fehrenheit:"))
cel=(fr-32)*5/9
print(cel)

[  0.         -11.66666667  25.          37.77777778]


In [2]:
#2
arr=np.random.rand(1000)
avg=np.mean(arr)
var=np.var(arr)
dev=np.std(arr)
print("Average: ",avg)
print("\nVariance: ",var)
print("\nDeviation: ",dev)

Average:  0.4953632975423767

Variance:  0.07972949561077698

Deviation:  0.2823641188444045


In [3]:
#3
dg=np.array([32,11,180,90])
rad=np.deg2rad(dg)
print(rad)

[0.55850536 0.19198622 3.14159265 1.57079633]


In [4]:
#4
arr=np.array([10,15,20,100])
dif=np.diff(arr)
print(dif)


[ 5  5 80]


In [5]:
#5
arr=np.array([9+2j,9+1j,1+2j,3+5j])
sor=np.sort(arr)
print(sor)

[1.+2.j 3.+5.j 9.+1.j 9.+2.j]


In [20]:
#6
arr=np.random.randint(0,10,size=10)
for i in arr:
    if i > 4:
        print(i)

7
9
7
6
5
6
9


In [7]:
#7
arr = np.random.randint(1, 10, size=10)
print("Array:", arr)

num = int(input("Enter a number "))

if num in arr:
    ind = np.where(arr == num)[0]
    print(f"{num} found at : {ind}")
else:
    print(f"Not found")


Array: [9 2 4 1 8 7 3 9 7 7]
1 found at : [3]


In [21]:
#8
arr = np.random.randint(1, 101, size=5)
print(" array:", arr)
np.savetxt('array.txt', arr)
loaded_arr = np.loadtxt('array.txt')
print("Loaded array:", loaded_arr)


 array: [44  9 85 26 80]
Loaded array: [44.  9. 85. 26. 80.]


In [9]:
#9
arr = np.arange(30, 61, 2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


In [22]:
#10
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

total_sum = np.sum(arr)

row_sum = np.sum(arr, axis=1)


col_sum = np.sum(arr, axis=0)

print("Total sum:", total_sum)
print("Row sums:", row_sum)
print("Column sums:", col_sum)


Total sum: 45
Row sums: [ 6 15 24]
Column sums: [12 15 18]
